spring:
  profiles:
    include: secrets
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${secrets.url}
    username: ${secrets.username}
    password: ${secrets.password}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      port: 6379
      host: ${secrets.redisHost}

logging.level:
  #  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
  org.springframework.cache: trace

jwt:
  #  30
  token.expired-time-ms: 2592000000
  secret-key: ${secrets.secret-key}