name: Deploy to EC2
on:
  pull_request:
    branches:
      - develop
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH to EC2 and Deploy1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/ubuntu/sns-project
            git pull origin develop
            echo ${{ secrets.APPLICATION_SECRET_YML }} | base64 --decode > ./src/main/resources/application-secrets.yml 
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -Xms128m -Xmx256m -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &

      - name: SSH to GCP and Deploy2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/nickchoi0515/sns-project
            whoami
            git pull origin develop
            echo ${{ secrets.APPLICATION_SECRET_YML }} | base64 --decode > ./src/main/resources/application-secrets.yml 
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -Xms128m -Xmx256m -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
